#![allow(clippy::clone_on_copy, clippy::manual_is_multiple_of)]
//! Cross-language differential test (DEVPLAN D10 / M0).
//!
//! Replays the golden vectors generated by `vectors/gen_vectors.py` from
//! `rsmt6a.py`, asserting that the Rust reference core produces **byte-identical**
//! roots, applied sets, and opcode streams — and that each round verifies.
//!
//! Regenerate with:
//!   python3 vectors/gen_vectors.py > crates/rsmt-core/tests/vectors.txt

use rsmt_core::{
    Op, Sha256RefHasher, Tree, Value32, bytes_to_limbs, limbs_to_bytes, verify_consistency,
};

type H = Sha256RefHasher;
type D = [u8; 32];

const VECTORS: &str = include_str!("vectors.txt");

fn hex32(s: &str) -> D {
    assert_eq!(s.len(), 64, "expected 32-byte hex, got {s:?}");
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap();
    }
    out
}

/// Parse an exact 32-byte value from 64 hex chars (R3-D1: values are `Value32`;
/// the corpus is regenerated with 32-byte values, so `"-"` no longer appears).
fn hex_value(s: &str) -> Value32 {
    Value32::new(hex32(s))
}

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Serialize a Rust op exactly as `gen_vectors.py` serializes the Python op.
fn serialize_op(op: &Op<D>) -> String {
    match op {
        Op::S(h) => format!("S {}", to_hex(h)),
        Op::O {
            depth,
            region,
            c_l,
            c_r,
        } => format!(
            "O {} {} {} {}",
            depth,
            to_hex(&limbs_to_bytes(region)),
            to_hex(c_l),
            to_hex(c_r)
        ),
        Op::OL { key, value } => {
            format!(
                "OL {} {}",
                to_hex(&limbs_to_bytes(key)),
                to_hex(value.as_bytes())
            )
        }
        Op::L => "L".to_string(),
        Op::N { depth } => format!("N {depth}"),
    }
}

fn opt_root(s: &str) -> Option<D> {
    if s == "none" { None } else { Some(hex32(s)) }
}

#[test]
fn differential_against_rsmt6a() {
    let mut lines = VECTORS.lines().peekable();
    let mut scenarios = 0usize;
    let mut rounds_total = 0usize;

    while let Some(line) = lines.next() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let name = line.strip_prefix("SCENARIO ").expect("SCENARIO header");
        scenarios += 1;
        let mut tree: Tree<H> = Tree::new();

        loop {
            let hdr = lines.next().unwrap().trim();
            if hdr == "ENDSCENARIO" {
                break;
            }
            assert_eq!(hdr, "ROUND", "scenario {name}");
            rounds_total += 1;

            // BATCH
            let n: usize = lines
                .next()
                .unwrap()
                .trim()
                .strip_prefix("BATCH ")
                .unwrap()
                .parse()
                .unwrap();
            let mut batch = Vec::with_capacity(n);
            for _ in 0..n {
                let l = lines.next().unwrap();
                let (kh, vh) = l.trim().split_once(' ').unwrap();
                batch.push((bytes_to_limbs(&hex32(kh)), hex_value(vh)));
            }

            // APPLIED (expected)
            let a: usize = lines
                .next()
                .unwrap()
                .trim()
                .strip_prefix("APPLIED ")
                .unwrap()
                .parse()
                .unwrap();
            let mut expect_applied = Vec::with_capacity(a);
            for _ in 0..a {
                let l = lines.next().unwrap();
                let (kh, vh) = l.trim().split_once(' ').unwrap();
                expect_applied.push((bytes_to_limbs(&hex32(kh)), hex_value(vh)));
            }

            let old = opt_root(lines.next().unwrap().trim().strip_prefix("OLD ").unwrap());
            let new = opt_root(lines.next().unwrap().trim().strip_prefix("NEW ").unwrap());

            // PROOF (expected serialized tokens)
            let m: usize = lines
                .next()
                .unwrap()
                .trim()
                .strip_prefix("PROOF ")
                .unwrap()
                .parse()
                .unwrap();
            let mut expect_proof = Vec::with_capacity(m);
            for _ in 0..m {
                expect_proof.push(lines.next().unwrap().trim().to_string());
            }
            assert_eq!(lines.next().unwrap().trim(), "ENDROUND");

            // -- replay in Rust --
            let old_before = tree.root_hash();
            assert_eq!(old_before, old, "scenario {name}: old root mismatch");

            let (applied, proof) = tree.batch_insert(batch);
            let new_after = tree.root_hash();
            assert_eq!(new_after, new, "scenario {name}: new root mismatch");
            assert_eq!(applied, expect_applied, "scenario {name}: applied mismatch");

            let got_proof: Vec<String> = proof.iter().map(serialize_op).collect();
            assert_eq!(
                got_proof, expect_proof,
                "scenario {name}: opcode stream mismatch"
            );

            // The stream must verify against the recorded roots.
            if !applied.is_empty() {
                let nr = new_after.clone().unwrap();
                verify_consistency::<H>(&proof, old_before.as_ref(), &nr, &applied)
                    .unwrap_or_else(|e| panic!("scenario {name}: verify failed: {e:?}"));
            }
        }
    }

    assert!(scenarios >= 10, "expected many scenarios, got {scenarios}");
    assert!(
        rounds_total >= 80,
        "expected many rounds, got {rounds_total}"
    );
    eprintln!("differential: {scenarios} scenarios, {rounds_total} rounds, all byte-identical");
}
